#!/bin/bash -ex

REPO=ibexa/oss-skeleton
VER=v4.6.32
COMMIT=bcd755b140abbf72a19c2231360a82b3f3408a1f

WEBROOT="/var/www/$(dirname $REPO)"
URL="https://github.com/$REPO"

git clone --depth 1 --branch="$VER" "$URL" "$WEBROOT"
test "$(git -C "$WEBROOT" rev-parse HEAD)" = "$COMMIT"
