#!/bin/bash -ex

DB_NAME=ibexa
DB_USER=ibexa
DB_PASS=$(mcookie)

WEBROOT=/var/www/ibexa

# disable composer memory limit for install
export COMPOSER_MEMORY_LIMIT=-1
# set turnkey-composer default "COMPOSER_HOME"
sed -i "\|^HOME_FALLBACK|s|=.*|=$WEBROOT|" /usr/local/bin/turnkey-composer

# tweak apache-credit
CONF=/etc/apache2/mods-available/substitute.conf
sed -i "s|</body>|</footer>|g" $CONF

cd $WEBROOT

# php.ini tweaks
PHPINI=/etc/php/8.4/apache2/php.ini
sed -i "s|^memory_limit.*|memory_limit = 256M|" $PHPINI
sed -i "s|^;date.timezone.*|date.timezone = \"America/Los_Angeles\"|" $PHPINI

# Debian names the Yarn executable yarnpkg.
ln -sf /usr/bin/yarnpkg /usr/local/bin/yarn

# configure apache
a2dissite 000-default
a2ensite ibexa
a2enmod rewrite

# start services
service mysql start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "CREATE USER $DB_USER@localhost IDENTIFIED BY '$DB_PASS'; GRANT ALL PRIVILEGES ON $DB_NAME.* TO $DB_USER@localhost;"

ENVFILE=$WEBROOT/.env

sed -i "s|APP_ENV=dev|APP_ENV=prod|" $ENVFILE
sed -i "s|^DATABASE_VERSION=.*|DATABASE_VERSION=mariadb-11.8.0|" $ENVFILE
sed -i "s|^DATABASE_URL=.*|DATABASE_URL=\"mysql://$DB_USER:$DB_PASS@localhost:3306/$DB_NAME?serverVersion=mariadb-11.8.0\\&charset=utf8mb4\"|" $ENVFILE

mkdir /var/www/ibexa/vendor
chown -R www-data:www-data /var/www/ibexa
install -d -o www-data -g www-data /var/www/.yarn
turnkey-composer install --no-dev --no-interaction
rm -rf /var/www/.yarn

php $WEBROOT/bin/console ibexa:install
php $WEBROOT/bin/console ibexa:graphql:generate-schema

chown -R www-data:www-data $WEBROOT/var

# stop services
service mysql stop
