#!/bin/bash -e
# set ibexa admin password and email

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/ibexa.py --pass="$APP_PASS" --email="$APP_EMAIL"

cd /var/www/ibexa
php -d memory_limit=256M bin/console cache:clear --env=prod
chown -R www-data:www-data var/cache
